# coding: utf-8

"""
    PlayHT API

    The PlayHT's API API allows developers to Realtime Text to Speech streaming Stream audio bytes from text, Convert long form Text to Speech Generate audio from text, and Voice Cloning Instant Cloning.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: devs@play.ht
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import playht
from playht.api.default_api import DefaultApi  # noqa: E501
from playht.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cloned_voices(self):
        """Test case for cloned_voices

        Obtains a list of all cloned voices created by the user.  # noqa: E501
        """
        pass

    def test_convert_ssml_to_speech(self):
        """Test case for convert_ssml_to_speech

        Convert SSML to Speech. It can generate text for Standard & Premium (S&P) voices. The identifiers for these voices look like 'en-US-JennyNeural'. If you are using PlayHT voices (their identifiers look like 'larry' or a URL).  # noqa: E501
        """
        pass

    def test_create_instant_voice_clone_url(self):
        """Test case for create_instant_voice_clone_url

        Create Instant Voice Clone (via file URL). Create an instant voice clone by providing an URL for a sample audio file.  # noqa: E501
        """
        pass

    def test_delete_cloned_voices(self):
        """Test case for delete_cloned_voices

        Delete Cloned Voices. Deletes a cloned voice created by the user using the provided voice_id.  # noqa: E501
        """
        pass

    def test_get_conversion_job_status(self):
        """Test case for get_conversion_job_status

        Get conversion job status. Gets text-to-speech job status and generated audio file URL.  # noqa: E501
        """
        pass

    def test_voices(self):
        """Test case for voices

        Gets the full list of stock PlayHT Voices available for use with the API.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
