# coding: utf-8

"""
    PlayHT API

    The PlayHT's API API allows developers to Realtime Text to Speech streaming Stream audio bytes from text, Convert long form Text to Speech Generate audio from text, and Voice Cloning Instant Cloning.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: devs@play.ht
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import playht
from playht.models.error_response import ErrorResponse  # noqa: E501
from playht.rest import ApiException


class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = playht.models.error_response.ErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
